---
- name: Create a mount point
  ansible.builtin.file:
    path: "{{ item | trim | split(' ') | last }}"
    state: directory
    mode: '0644'
    recurse: true
  with_items: "{{ nfs_mount_points }}"

- name: Mount the NFS share
  ansible.posix.mount:
    path: "{{ item | trim | split(' ') | last }}"
    src: "{{ item | trim | split(' ') | first }}"
    fstype: nfs
    state: mounted
  with_items: "{{ nfs_mount_points }}"