---
- name: Install NFS server (Debian)
  ansible.builtin.apt:
    name:
      - nfs-common
      - nfs-kernel-server
    update_cache: true
    state: present
  when: not nfs_client

- name: Install NFS client (Debian)
  ansible.builtin.apt:
    name:
      - nfs-common
    update_cache: true
    state: present
  when: nfs_client