---
# Include variables and define needed variables
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

# Include OS specific tasks
- name: Include OS-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"

# Include task to setup NFS
- name: Setup NFS server
  block:
    - name: Setup NFS
      ansible.builtin.include_tasks: setup.yml
      with_items: "{{ nfs_exports }}"
    
    - name: Update /etc/exports
      ansible.builtin.template:
        src: exports.j2
        dest: /etc/exports
        owner: root
        group: root
        mode: '0644'
      notify: restart_nfs

    - name: Make sure a NFS is running
      ansible.builtin.systemd:
        state: started
        name: "{{ nfs_service_name }}"
        enabled: true
  when: not nfs_client

- name: Setup clients
  ansible.builtin.include_tasks: client.yml
  when: nfs_client
  with_items: "{{ nfs_mount_points }}"
