---
test:ansible-lint:
  stage: test
  before_script:
    - pip install ansible==$ANSIBLE_VERSION ansible-lint yamllint
  script:
    - ansible-lint -v
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_TAG'
      when: never
    - if: '$CI_COMMIT_BRANCH != "develop" && $CI_PIPELINE_SOURCE == "push"'
      when: manual
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" && $CI_PIPELINE_SOURCE == "merge_request_event"'
  tags:
    - docker.sock

test:yamllint:
  stage: test
  before_script:
    - pip install ansible==$ANSIBLE_VERSION ansible-lint yamllint
  script:
    - yamllint .
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_TAG'
      when: never
    - if: '$CI_COMMIT_BRANCH != "develop" && $CI_PIPELINE_SOURCE == "push"'
      when: manual
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" && $CI_PIPELINE_SOURCE == "merge_request_event"'
  tags:
    - docker.sock

test:molecule:
  stage: test
  variables:
    PY_COLORS: 1
  script:
    - molecule test
  parallel:
    matrix:
      - MOLECULE_PLATFORM_IMAGE: 
          - geerlingguy/docker-ubuntu1804-ansible:latest
          - geerlingguy/docker-ubuntu2004-ansible:latest
          - geerlingguy/docker-ubuntu2204-ansible:latest
          - geerlingguy/docker-rockylinux8-ansible
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_TAG'
      when: never
    - if: '$CI_COMMIT_BRANCH != "develop" && $CI_PIPELINE_SOURCE == "push"'
      when: manual
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" && $CI_PIPELINE_SOURCE == "merge_request_event"'
  tags:
    - docker.sock 
