---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: nfs-server
    image: ${MOLECULE_PLATFORM_IMAGE:-geerlingguy/docker-centos8-ansible:latest}
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
  - name: nfs-client
    image: ${MOLECULE_PLATFORM_IMAGE:-geerlingguy/docker-centos8-ansible:latest}
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: testinfra
  # options:
  #   connection: docker
  #   v: 2
    # s:
lint: |
  set -e
  yamllint .
  ansible-lint -v
